### PR TITLE
Fix suds cache example in README

### PR DESCRIPTION
**Pull request by mpaolino**
FileCache is not meant to be used directly but as a base for other implementations, it will throw and exception if you try to use it directly. 
```
raised unexpected: AttributeError("'str' object has no attribute 'root'",)
```
More details [here](https://bitbucket.org/jurko/suds/issues/47/caching-error-when-getting-document-root).

You need to use one of its implementations, or provide your own, in this case `suds.cache.DocumentCache `seems a pretty decent working alternative.

### CODE REVIEW

**Comment by msaniscalchi** [comment]
Hey Miguel,

Thanks for the report! So, I'm trying to understand the core problem used as the basis for this pull request. It sounds like you expect `suds.cache.FileCache` to be abstract, but [that doesn't seem to be the case](https://bitbucket.org/jurko/suds/src/0fcfff1ea149397bfa23c7537a0ae2ac300e9564/suds/cache.py?at=release-0.6&fileviewer=file-view-default#cache.py-91).

I can't reproduce the `AttributeError` you're describing via typical usage; are there specific steps I can take to reproduce?

Thanks,
Mark

**Comment by mpaolino** [comment]
Sure thing, edit the global vars and try this (sorry its not very polished, just a rough example):

```python
#!/usr/bin/env python
#
import logging
import suds
from googleads.adwords import AdWordsClient
from googleads.oauth2 import GoogleRefreshTokenClient

logging.basicConfig(level=logging.INFO)
logging.getLogger('suds.transport').setLevel(logging.DEBUG)

CLIENT_ID = 'your_client_id' 
CLIENT_SECRET = 'your_client_secret'
REFRESH_TOKEN = 'your_refresh_token'
DEV_TOKEN = 'your_dev_token'
CUSTOMER_ID = 'your_customer_id'
CAMPAIGN_NAME = 'your_campaign_name'
CACHE_PATH = './sudscache'

def main(client, campaign_name):
    # Initialize appropriate service.
    campaign_service = client.GetService('CampaignService', version='v201702')

    # Construct selector and get all campaigns.
    offset = 0
    selector = {
        'fields': ['Id', 'Name', 'Status'],
        'predicates': [
            {
                'field': 'Name',
                'operator': 'EQUALS',
                'values': [campaign_name]
            },
        ]
    }

    res = campaign_service.get(selector)

    # Display results.
    if 'entries' in res:
        for campaign in res['entries']:
            print ('Campaign with id \'%s\', name \'%s\', and status \'%s\' was '
                   'found.' % (campaign['id'], campaign['name'],
                               campaign['status']))
    else:
        print 'No campaigns were found.'


if __name__ == '__main__':
    file_cache = suds.cache.FileCache(location=CACHE_PATH, days=2)
    credentials = GoogleRefreshTokenClient(CLIENT_ID, CLIENT_SECRET, REFRESH_TOKEN)
    adwords_client = AdWordsClient(DEV_TOKEN, credentials, 'SuperDuperAgent/0.0.1',
                                   client_customer_id=CUSTOMER_ID,
                                   cache=file_cache)
    main(adwords_client, CAMPAIGN_NAME)
```

My requirements.txt:
```python
appdirs==1.4.3
googleads==5.3.0
httplib2==0.10.3
oauth2client==4.0.0
packaging==16.8
pkg-resources==0.0.0
pyasn1==0.2.3
pyasn1-modules==0.0.8
pycodestyle==2.3.1
pyparsing==2.2.0
PySocks==1.6.7
pytz==2017.2
PyYAML==3.12
rsa==3.4.2
six==1.10.0
suds-jurko==0.6
xmltodict==0.10.2
```

**Comment by mpaolino** [comment]
Oh, you  need to execute it TWICE.

**Comment by msaniscalchi** [comment]
I see what you're referring to now. The misunderstanding actually stemmed from our `__init__` doc comments for `AdWordsClient` and `DfpClient`, which state that [not specifying a cache would cause a FileCache to be used by default](https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L300). That is incorrect, it is [`ObjectCache` that is used by default](https://bitbucket.org/jurko/suds/src/0fcfff1ea149397bfa23c7537a0ae2ac300e9564/suds/client.py?at=release-0.6&fileviewer=file-view-default#client.py-111).

You're correct, actually manually specifying a FileCache as suggested would cause an AttributeError, so the premise behind this PR certainly makes sense.

Could you also modify this PR to fix the doc comments in [`AdWordsClient`](https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L300) and [`DfpClient`](https://github.com/googleads/googleads-python-lib/blob/master/googleads/dfp.py#L217)?

**Pull request merged**
