### PR TITLE
Python3?

### PR DESCRIPTION
**Pull request by rca**
```
[berto@g6]$ python generate_refresh_token.py --client_id ${GOOGLE_CLIENT_ID} --client_secret ${GOOGLE_CLIENT_SECRET}
  File "generate_refresh_token.py", line 58
    print 'After approving the token enter the verification code (if specified).'
                                                                                ^
SyntaxError: invalid syntax
```

### CODE REVIEW

**Comment by rca** [comment]
I signed it!

**Comment by msaniscalchi** [comment]
Hello, thanks for submitting a pull request! As an FYI, this library and its examples are written in Python 2, but use the 2to3 utility for Python 3 compatibility. The example you're referring to should be available and compatible with Python 3 on our [releases page](https://github.com/googleads/googleads-python-lib/releases).

We will not be accepting this pull request because it is expected behavior for the library to not be Python 3 compatible prior to being run through the 2to3 convertor.

Regards,
Mark

**Comment by rca** [comment]
Hey Mark,

Thanks for the update. I cloned the repo to run the examples from there.  Which i did while following instructions for getting a refresh token.

In the online docs outlining the process I do not recall a link or mention to an examples download. 

Thanks.

**Comment by msaniscalchi** [comment]
I see. It's possible that the doc you read might have been misleading for Python 3 users. If you could point me in the direction of the specific documentation in question, I'll make a note of this so that we can fix it.

**Comment by rca** [comment]
@msaniscalchi, my pleasure.  The docs start here:

https://developers.google.com/adwords/api/docs/guides/first-api-call#set_up_oauth2_authentication

Search for the heading _"Get an OAuth2 refresh token and configure your client"_.

The Python tab leads you to this page on GitHub:

https://github.com/googleads/googleads-python-lib/wiki/API-access-using-own-credentials-(installed-application-flow)#step-2---setting-up-the-client-library

Section _"Step 2"_ says to run the example program.  Initially I assumed it would already be installed after running `pip install googleads`.  My second assumption was simply to download the file or clone the entire repo; I did the latter.

**Pull request closed without merging**
